/* ════════════════════════════════════════════════════════════════
   WHATSAPP.JS
   WhatsApp integration: builds and opens wa.me links for CTAs and the contact form.
════════════════════════════════════════════════════════════════ */

    /* ════════════════════════════════════════════════════════════════
       WHATSAPP INTEGRATION
       CUSTOMIZE: Add new source keys and messages to the msgs object.
    ════════════════════════════════════════════════════════════════ */
    function openWA(source) {
      const msgs = {
        'nav': `Hi SlideCraft! I'd like to place an order.`,
        'hero': `Hi SlideCraft! I saw your website and I'd like to start a project.`,
        'sticky': `Hi SlideCraft! I'd like to discuss a project.`,
        'footer': `Hi SlideCraft! I have a question.`,
        'cta': `Hi SlideCraft! I'm ready to get started.`,
        /* Pricing tier sources — auto-generated by buildPricingGrid */
        'pricing-essential': `Hi SlideCraft! I'd like to order the Essential presentation package (₹199).`,
        'pricing-professional': `Hi SlideCraft! I'd like to order the Professional presentation package (₹299).`,
        'pricing-enterprise': `Hi SlideCraft! I'd like to order the Enterprise presentation package (₹499).`,
        'pricing-mini-project': `Hi SlideCraft! I'm interested in the Mini Arduino Project (₹499).`,
        'pricing-academic-project': `Hi SlideCraft! I'm interested in the Academic Arduino Project (₹999).`,
        'pricing-competition-project': `Hi SlideCraft! I'm interested in the Competition Arduino Project (₹1999+).`,
      };
      /* Fallback: if source starts with "pricing-", make a generic tier message */
      let msg = msgs[source];
      if (!msg && source.startsWith('pricing-')) {
        const tier = source.replace('pricing-', '').replace(/-/g, ' ');
        msg = `Hi SlideCraft! I'd like to enquire about the ${tier} plan.`;
      }
      msg = msg || `Hi SlideCraft! I'd like to enquire about your services.`;
      window.open(WA_BASE + encodeURIComponent(msg), '_blank');
    }

    function handleFormSubmit(e) {
      e.preventDefault();
      const form = e.target;
      const name = form.querySelector('input[type="text"]')?.value || '';
      const service = form.querySelector('select')?.value || 'general enquiry';
      const message = form.querySelector('textarea')?.value || '';
      const waMsg = `Hi SlideCraft! I'm ${name}.\nService: ${service}\n${message ? 'Details: ' + message : ''}`;
      window.open(WA_BASE + encodeURIComponent(waMsg), '_blank');
    }

